# 设置 vm.max_map_count 262144
- name: set vm.max_map_count
  sysctl:
    name: vm.max_map_count
    value: 262144
    state: present
    reload: yes
  tags:
    - sysctl

# 开启ping
- name: enable ping
  sysctl:
    name: net.ipv4.icmp_echo_ignore_all
    value: 1
    state: present
    reload: yes
