# install packages 
- name: install required packages
  yum: name={{item}} state=latest
  with_items:
    - yum-utils

# 安装 docker 的 yum 源 (docker ce)
- name: install docker ce repo
  command: yum-config-manager --add-repo http://mirrors.aliyun.com/docker-ce/linux/centos/docker-ce.repo

# 安装 docker-ce-18.06.1.ce
- name: install docker ce-18.06.1.ce
  yum: name=docker-ce-18.06.1.ce state=present
