# 修改hostname
- include_tasks: hostname.yml

# install packages 
- name: install required packages
  yum: name={{item}} state=latest
  with_items:
    - lvm2
    - yum-utils
    - device-mapper-persistent-data

# 关闭selinux
- name: close selinux
  selinux: state=disabled

# 修改内核参数
- include_tasks: modify-sysctlconf

# 格式化数据盘
- include_tasks: format-data-disk.yml
