- name: Update /etc/hosts from inventory
  lineinfile: 
    path: /etc/hosts 
    regexp: '.*{{item}}$' 
    line: '{{ hostvars[item].ansible_host }} {{item}}' 
    state: present
  with_items: '{{groups.all}}'
