# 设置 net.bridge.bridge-nf-call-ip6tables
- name: set net.bridge.bridge-nf-call-ip6tables
  sysctl:
    name: net.bridge.bridge-nf-call-ip6tables
    value: 1
    state: present
    reload: yes
  tags:
    - sysctl

# 设置 net.bridge.bridge-nf-call-iptables
- name: set net.bridge.bridge-nf-call-iptables
  sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: 1
    state: present
    reload: yes
  tags:
    - sysctl
